### ISSUE TITLE
Roadmap: Alpha Release

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#100]
Below is a list of what is required for an Alpha release.

### Necessary Basic Static Methods
I'm cherry-picking from current RxJS2

- [x] concat
- [x] empty
- [x] from
- [x] fromArray
- [x] fromEvent
- [x] fromEventPattern
- [x] fromPromise
- [x] interval
- [x] just/value
- [x] merge
- [x] never
- [x] of
- [x] range
- [x] return
- [x] throw
- [x] timer
- [x] zip

### Necessary Basic Operators 

I'm cherry-picking [operators from RxJS 2](https://github.com/Reactive-Extensions/RxJS/tree/master/doc/api/core/operators) for now. I'm trying to narrow it down to what's essential to implement.

- [x] buffer
- [x] bufferCount (bufferWithCount)
- [x] bufferTime (bufferWithTime)
- [x] bufferToggle (buffer(obs, fn))
- [x] bufferWhen (buffer(fn))
- [x] catch
- [x] combineLatest
- [x] concat
- [x] concatAll
- [x] defaultIfEmpty
- [x] delay
- [x] flatMap
- [x] filter
- [x] forkJoin
- [x] groupBy
- [x] groupByUntil
- [x] map
- [x] mapTo
- [x] merge
- [x] mergeAll
- [x] multicast
- [x] observeOn
- [x] publish
- [x] reduce
- [x] repeat
- [x] retry
- [x] retryWhen
- [x] scan
- [x] skip
- [x] skipUntil
- [x] startWith
- [x] subscribeOn
- [x] switchMap (flatMapLatest)
- [x] take
- [x] takeUntil
- [x] timeout
- [x] toArray
- [x] toPromise
- [x] window
- [x] windowCount (windowWithCount)
- [x] windowTime (windowWithTime)
- [x] windowToggle (window(obs, fn))
- [x] windowWhen (window(fn))
- [x] withLatestFrom
- [x] zip
- [x] zipAll

### Necessary Support Types

(Not including Observable and Subscriber, which are a given)

- [x] BehaviorSubject
- [x] ConnectableObservable (multicast)
  - [x] refCount
- [x] Subject
- [x] ReplaySubject

### Schedulers

- [x] immediate
- [x] nextTick

### Macro Performance Tests

We want to add macro performance tests for all operators that create other Observables or Subscriptions internally. (Basically anything that does a lot of allocating) We may expand this to anything that buffers or schedules. These should be contrasted against their predecessors.

- [x] combineLatest
- [x] flatMap
- [x] flatMap with Scalar
- [x] groupBy
- [x] merge
- [x] mergeAll
- [x] windowCount (windowWithCount)

(Moved the rest to #351)

### Micro Performance Tests

Micro performance tests are perhaps slightly less reliable than the macro performance tests, but still give us some insight into how we're doing. For this, we'll want to have all operators compared to previous versions (if there is one)

#### Creation

- [x] concat
- [x] empty
- [x] from
- [x] fromArray
- [x] merge
- [x] of
- [x] range
- [x] return
- [x] throw

(Moved the rest to #352)

#### Operators

- [x] bufferCount (bufferWithCount)
- [x] catch
- [x] combineLatest
- [x] concat
- [x] concatAll
- [x] defaultIfEmpty
- [x] flatMap
- [x] filter
- [x] groupBy
- [x] groupByUntil
- [x] map
- [x] merge
- [x] mergeAll
- [x] reduce
- [x] repeat
- [x] scan
- [x] skip
- [x] startWith
- [x] take
- [x] toArray
- [x] windowCount (windowWithCount)
- [x] zip

(Moved the rest to #350 )

Just as a general benchmark, we can test all operators against previous versions of themselves.
### Other Requirements

- [x] some basic documentation
- [x] community code of conduct
- [x] install instructions
- [x] build instructions
- [x] basic build pipeline
- [x] license
- [x] Travis integration
- [x] npm publishing
- [x] solid version starting point (4.0.0-alpha?)
- [x] interop points from [es-observable spec](/zenparsing/es-observable). (Observable.from and Observable.prototype[Symbol.observable]? TBD)
- [x] Namespace to Rx from RxNext

**Comment by robwormald** [comment]
a partition operator would be useful when dealing with forms:

```js 
//split off empty queries to reset form data
const [queryStream, emptyQueryStream] = searchStream.partition(val => val.length > 1);
//search with values
const queryResultsStream = queryStream.flatMapLatest(val => youtube.search(val));
//reset results to empty
const emptyQueryResultsStream = emptyQueryStream.map(val => []);
//use in view
this.searchResults = queryResultsStream.merge(emptyQueryResultsStream)
```

**Comment by blesh** [comment]
@robwormwald probably a separate issue. But I think you could accomplish this with `groupBy` more effectively. `searchStream.groupBy(x => x.length > 0)` would break the values into two observables, but only if it had to.

**Comment by staltz** [comment]
Probably missing `combineLatest` static operator, since you have also static zip and static merge.

**Comment by blesh** [comment]
@staltz hah. Yah I thought of that while I was in the car on my way home

**Comment by jeremymwells** [comment]
Do we have any guidelines for documentation? Is the intent to mimic the current RxJS' wiki documentation?

**Comment by robwormald** [comment]
I have a (suuuuuper basic) dgeni er, generator setup im about to merge in for generating API docs from the codebase. It's got a liitle hook for "guides" or whatever else we might like to stick in alongside. I was sort of winging it until somebody came up with a better idea.

**Comment by jeremymwells** [comment]
i like dgeni.

**Comment by blesh** [comment]
Updated to add checkboxes for performance tests

**Comment by blesh** [comment]
Updated window and buffer names

**Comment by blesh** [comment]
Moving the remaining perf test additions to their own issues and putting them on [Initial Beta Release](https://github.com/ReactiveX/RxJS/milestones/Initial%20Beta) milestone.

I think we've done enough here, and we already have multiple projects using this library, so it's already being "Alpha'ed", so to speak. Time to move on....
