### ISSUE TITLE
Roadmap to release (leaving Beta)

### ISSUE THREAD

**Issue by blesh** [ReactiveX/rxjs#1060]
This is just a start for a road map:

- [x] automated tests in all platforms
- [ ] update reactivex.io documentation
- [ ] updated migration documentation
- [ ] all operators and public APIs have inline docs
- [ ] PNG marble diagrams generated for every operator
- [ ] improved documentation on Schedulers, what they are and what they do.
- [ ] publish all Jasmine test helpers as separate global and module
- [x] ensure type definition / signature would be correct for typescript-based consumers

**Comment by kwonoj** [comment]
Maybe can add below?

- ensure type definition / signature for typescript interface would be correct for typescript-based consumers (also having logistics to test those)

**Comment by staltz** [comment]
> all operators and public APIs have inline docs

Maybe add "and their respective PNG diagrams" to this?

**Comment by blesh** [comment]
done and done.

**Comment by blesh** [comment]
Given that the checkboxes in this issue are too generic to "check". I'm going to close this issue for now. Each of those items should really be tracked in their own issues.
