### ISSUE TITLE
Triage work 08-2019

### ISSUE THREAD

**Issue by BioPhoton** [ReactiveX/rxjs#4970]
Dear Core-Team. 

I collected these issues as from my humble opinion they could be closed.
All listed issues are suggestions. I don't want to make people upset that opened issues a while ago and did not get a fully satisfying solution yet! So please consider these list as a suggestion, not a definite thing!
I will add a lot more issues in the next days here. Just that you know it is a growing list.

If any contributors see this and maybe have some more information on why their issue is still relevant, please add the information to the issue as a comment. I will do my best to help you further.

I hope this can help to get some outdated issues closed. :)

## Opened by or related to Core-Team

- [ ] [Where to put the unhandled error event hook? Looking for ideas/thoughts](https://github.com/ReactiveX/rxjs/issues/3004) 
can be closed by @benlesh as the PR is merged
- [ ] [Remove secondary mappings for flattening operators in v6?](https://github.com/ReactiveX/rxjs/issues/2929)
@benlesh we can close this issue as already merged. 
- [ ] [Eliminate @reactivex/rxjs publish in 6.0?](https://github.com/ReactiveX/rxjs/issues/2916)
@benlesh we can close this as it’s already implemented
- [ ] [Add close state to finally operator?](https://github.com/ReactiveX/rxjs/issues/2823) 
- [ ] [Add information on README about documentation effort](Add information on README about documentation effort) 
can be closed as it's already done. Can be approved by @JWO179
- [ ] [Docs on Observable methods are all duplicated](https://github.com/ReactiveX/rxjs/issues/3526) 
can be closed as docs are updated. Double check with @JWO179 
- [ ] [‘distinct’ can't work as the description in tutorials](https://github.com/ReactiveX/rxjs/issues/3069) 
Even the author is right with that the docs for `distinct` uses a lot of confusing wording, his concern about wrong functionality is wrong. We can close it. @JWO179 we could rethink the used words in the documentation
- [ ] [Autopublish nightly package](https://github.com/ReactiveX/rxjs/issues/3008) 
ask @kwonoj to close it
- [ ] [Discuss module structure for 6.0](https://github.com/ReactiveX/rxjs/issues/2912)
could most likely be closed by @benlesh

## Opened by contributors

- [ ] [Node Require() Support](https://github.com/ReactiveX/rxjs/issues/3607) 
- [ ] [RxJS v6 TimeoutError is missing name property](https://github.com/ReactiveX/rxjs/issues/3602)
can be closed because it’s already implemented. See: https://github.com/ReactiveX/rxjs/pull/3656
- [ ] [Remove static `create` methods and provide importable functions instead](https://github.com/ReactiveX/rxjs/issues/3513)
can be closed as docs are updated. 
- [ ] [BehaviorSubject created with "create" does not have getValue() method](https://github.com/ReactiveX/rxjs/issues/1890) 
can be closed because it’s obsolete because we dropped `getValue`
- [ ] [Get response url from response.xhr on ie11](https://github.com/ReactiveX/rxjs/issues/3472)
See: https://github.com/ReactiveX/rxjs/issues/3472#issuecomment-379518028
- [ ] [Split creation functions from creation functions with Schedulers](https://github.com/ReactiveX/rxjs/issues/3264)
We can close this as it is already done.
- [ ] [Transducer Support](https://github.com/ReactiveX/rxjs/issues/3193)
can be closed as related to RxJs4 and just a question that is already answered.
- [ ] [Add flush functionality to distinctUntilChanged](https://github.com/ReactiveX/rxjs/issues/3142)
can be closed as it is already answered and the creator reconsidered his proposal
- [ ] [Documentation missing for operators in typescript declaration files](https://github.com/ReactiveX/rxjs/issues/3126)
- [ ] [bufferTime and bufferCount will mutate current buffer if a source is a subject that emits in the subscription for that buffer](https://github.com/ReactiveX/rxjs/issues/3001)
can be closed as it is by design
- [ ] [Handle stream like maybe monad](https://github.com/ReactiveX/rxjs/issues/2930)
can be closed, if the creator does not do it, as it is answered
- [ ] [Lettable operators: scope hoisting prevents dead code removal](https://github.com/ReactiveX/rxjs/issues/2981)
quite sure this can be closed
- [ ] [Add selector to publishReplay](https://github.com/ReactiveX/rxjs/issues/2844)
can be closed as already implemented
- [ ] [AJAX response with status 0 must throw an error](https://github.com/ReactiveX/rxjs/issues/3606)
can be closed because it’s already implemented in 6.4.*. See: https://github.com/ReactiveX/rxjs/issues/3606#issuecomment-488614083
- [ ] [AJAX Content-Type Handling](https://github.com/ReactiveX/rxjs/issues/2837)
consider to close in favour of fromFetch
- [ ] [AJAX responseType Handling](https://github.com/ReactiveX/rxjs/issues/2835)
consider to close in favour of fromFetch
- [ ] [Observable AJAXPOST with wrong Content-Type after PUT](https://github.com/ReactiveX/rxjs/issues/2801)
- [ ] [Rx.Observable.AJAX onProgress only set for Upload](https://github.com/ReactiveX/rxjs/issues/2833)
consider to close in favour of fromFetch. Other suggestion, switch to immutable header object
- [ ] [AJAX config & intercept](https://github.com/ReactiveX/rxjs/issues/2686)
The discussion here is pretty much dead. Also we could consider to close in favour of fromFetch
- [ ] [Guidance on improving WebSocketSubject multiplex method](https://github.com/ReactiveX/rxjs/issues/2766)
- [ ] [WebSocketSubjectConfig's resultSelector is accepting a not necessary generic type T](https://github.com/ReactiveX/rxjs/issues/2754)

## Very old issues IMHO most probably outdate

- [ ] [SafeSubscriber does not unsubscribe itself](https://github.com/ReactiveX/rxjs/issues/2675) => pinged @jayphelps already
- [ ] [Make fromPromise support promise cancellation?](https://github.com/ReactiveX/rxjs/issues/2652)
- [ ] [Strongly type Observable Error](https://github.com/ReactiveX/rxjs/issues/2646)
- [ ] [TypeScript 2.1+ and Errors](https://github.com/ReactiveX/rxjs/issues/2612)
- [ ] [bufferTime minBufferSize](https://github.com/ReactiveX/rxjs/issues/2601) => IMHO to be closed because we have a solution and the operator extension is maybe a bigger discussion as It might include all other buffer maybe also windowing operators.  
- [ ] [Automated Publish](https://github.com/ReactiveX/rxjs/issues/2597) => could be closed as the current process is different and already includes a publishing strategy.

**Comment by benlesh** [comment]
This is AWESOME! Thanks for doing this, @BioPhoton!

**Comment by benlesh** [comment]
@kwonoj can you please look at the ajax related stuff above? I think that you were working on something around that.

**Comment by BioPhoton** [comment]
Welcome!

**Comment by llorenspujol** [comment]
@BioPhoton I think this issue/feature: https://github.com/ReactiveX/rxjs/issues/3430 is interesting to solve. I have added a 'mini-explanation' on the issue about it.

**Comment by KeijiBranshi** [comment]
Am seeing several open docs issues with merged PRs associated with them. Just wondering if they should also be closed out or not.
- [docs]: Operator `toArray` is missing documentation #4613
- [docs]: Operator `timestamp` is missing the short description, description, and examples #4615 
- [docs]: Operator `single` is missing the description, and examples #4616 
- [docs]: Operator `ignoreElements` is missing the description, and examples #4618
- [docs]: Operator `generate` need a total over whole of the documentation #4672

**Comment by niklas-wortmann** [comment]
thanks for the reminder @KeijiBranshi
