### ISSUE TITLE
Non-type-related issues for v7 beta

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#5372]
This issue is for tracking non-type-related issues - type-related issues are in https://github.com/ReactiveX/rxjs/issues/5066 - that could/should be addressed in the v7 beta.

* [x] Use `hostReportError` for swallowed errors - https://github.com/ReactiveX/rxjs/issues/5370 (From @benlesh: Here we opted to add a skipped test that we can "unskip" when we get to the larger refactor in v8)
* [x] `console.warn` still seems to be used instead of `hostReportError` - see [this comment](https://github.com/ReactiveX/rxjs/pull/5676#pullrequestreview-474139791)
* [x] Several issues related to the behaviour of notification observables that complete - https://github.com/ReactiveX/rxjs/issues/3665, https://github.com/ReactiveX/rxjs/issues/3853, https://github.com/ReactiveX/rxjs/issues/5379 - these (and the documentation) should be made consistent. I suspect that `audit` has this problem, too. <s>All operators that have a notifier need to be checked. (the only remaining PR on this one is here: https://github.com/ReactiveX/rxjs/pull/5769)</s> Nope, there are a whole bunch of operators that treat `next` and `complete` identically in notifiers/selectors. See #5838 and #5853 (the PR)
* [x] `mergeScan` has strange behaviour upon the completion of the inner observable - [see here](https://github.com/ReactiveX/rxjs/blob/674e540747f65febe8b87bc05f7ed764f0f33245/src/internal/operators/mergeScan.ts#L65) - this should be changed. (PR here: https://github.com/ReactiveX/rxjs/pull/5805)
* [x] `animationFrames` should use the API's `DOMHighResTimeStamp` - https://github.com/ReactiveX/rxjs/issues/5194
* [x] `finalize` is dodgy AF - see https://github.com/ReactiveX/rxjs/issues/5357 and issues linked therein.
* [x] `Subscribable` sources without `Symbol.observable` - see https://github.com/ReactiveX/rxjs/issues/4532
* [x] Scheduler exports - see https://github.com/ReactiveX/rxjs/issues/5421
* [ ] `@internal` - see #5768
* [ ] We should document that the minimum TypeScript `lib` for RxJS is `ES2018`, as that's when async iterables were introduced. That issue is that, our type inference tests assume that the types in `ES2018` are available and weird things can happen if they are not. See #5708. #5807 adds a workaround, but I think it's still worth documenting. Maybe reference [this blog post](https://ncjamieson.com/til-explicit-typescript-lib-references/)? Not sure where this would go in the docs.
* [ ] user-land operator subscriber - see https://github.com/ReactiveX/rxjs/issues/5836

Do Not Block The Release

* [ ] `concurrency` parameter for `conactMap` - see https://github.com/ReactiveX/rxjs/issues/5519 ([`mergeInternals`](https://github.com/ReactiveX/rxjs/pull/5754) could be extended to take a `concat` or `collate` flag)
* [ ] deprecations (breaking change documentation DOES block the release, but not the deprecations, as they're non-breaking): #4776; #5404

**Comment by benlesh** [comment]
`finalize` isn't really an issue. Just a confusing outcome from the implementation fo `concatMap` and a synchronous inner observable.

**Comment by cartant** [comment]
@benlesh

> `finalize` isn't really an issue.

I disagree. IMO, the`finalize` teardown is called too early. It's called before child subscriptions are finalized and that is the opposite order to both `complete` and `unsubscribe` calls.

Consider this snippet:

```ts
defer(() => {
  console.log(">1");
  return defer(() => {
    console.log(">2");
    return defer(() => {
      console.log(">3");
      return of(42).pipe(
        tap({ complete: () => console.log("c3") }),
        finalize(() => console.log("f3")),
        unsubscribed(() => console.log("u3"))
      );
    }).pipe(
      tap({ complete: () => console.log("c2") }),
      finalize(() => console.log("f2")),
      unsubscribed(() => console.log("u2"))
    );
  }).pipe(
    tap({ complete: () => console.log("c1") }),
    finalize(() => console.log("f1")),
    unsubscribed(() => console.log("u1"))
  );
}).subscribe();
```

which outputs:

```
>1  
>2  
>3  
c3  
c2  
c1  
f1  
f2  
f3  
u3  
u2  
u1  
```
