### ISSUE TITLE
[WIP] Roadmap V7

### ISSUE THREAD

**Issue by niklas-wortmann** [ReactiveX/rxjs#5795]
This is not official (yet). This is only the stuff that I have in mind that has to be done/should be done before V7 can be officially published. I hope we can fill this issue with V7 related issues and prs for more transparency around this release.

[Smaller Bundle Size]

- [x] Smallify all the operators (@benlesh )

[Typings]

- [x] Update the signatures to use variadic tuples for N-args support #5066

[Other Isssues]

- [x] Non-type-related issues for v7 #5372

[Features]

- [x] Reworking Multicasting: share, connect, and makeConnectable #5634
- [x] add switchScan() operator #4442

[Docs]
- [x] Documentation around breaking changes and deprecations #4776
- [x] Versioning #5794 #5793 #5792
- [x] final preparation #5911 #5912

**Comment by cartant** [comment]
Closing this 'cause everything listed has been checked off - i.e. closed or merged.
