### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by staltz** [ReactiveX/RxJS#58]
Edit this issue to...

- [ ] Replace this with something that should be done
- [ ] Replace me too
- [ ] Replace... you got the idea

**Comment by blesh** [comment]
I think I'd rather put a Roadmap in a .md file in the repo. Just so we can keep a better history. But you're right, we need a road map.

**Comment by staltz** [comment]
As you wish, I just tried to get things moving.

**Comment by blesh** [comment]
:) Appreciated, @staltz ... leaving this open until their is a valid roadmap.

**Comment by blesh** [comment]
Closing in favor of #100
