### ISSUE TITLE
Version 7 -> 8 Roadmap

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#6367]
# TBD (not actionable yet)

This issue is to come up with what the roadmap is for version 7-8.

### In Version 7

- [ ] `groupBy` config (#5679)
- [ ] Add all exports to top level
- [ ] ??? TBD

### In Version 8

- [ ] Remove _all_ deprecated APIs.
- [ ] Drop all Internet Explorer support into a pit of flames! 🔥 IE 🔥 🥳 
- [ ] ??? TBD

**Comment by criskrzysiu** [comment]
🔥 IE 🔥 🥳 - every time I see that statement in some repo it makes my day better

**Comment by MaximeBernard** [comment]
Since "??? TBD" seems to imply we can suggest anything, what about https://github.com/ReactiveX/rxjs/issues/2686?

It seems to be a recurring "issue" people are having to configure headers for every request (most popular seem to be `Bearer`, `CorrelationId` and `Content-Type`).

While it's not "hard" to make your own `ajax`, I feel it's a bit sad everyone has to write that piece of code and it might be helpful for everyone to have an helper provided by `rxjs`.

**Comment by PowerKiKi** [comment]
Wouldn't publishing multiple packages for what is essentially the same code actually increase risk of non tree shakable use-case and thus increase bundle size ?

As seen with lodash, if one of my dependency decides to depends on the future `@rxjs/observable`, but my app depends on the current `rxjs`, then all the code from `@rxjs/observable` will essentially be bundled twice, won't it ?

And of course it would be much worse if we actually publish a package for each operator. Then a single operator could be bundled three times if my deps happened to depend on `rxjs`, `@rxjs/operators` and say `@rxjs/operators-map`.

I could also imagine compatibility issues if one of my dependency depends on an old version of  `@rxjs/observable` and my app pass one of those object to a new, incompatible version of an operator coming from the latest version of `rxjs`. This kind of issue already happened with the `graphql` package where they had to add manual check in their code to throw error if it happens.

That seems a lot of tricky tradeoffs to attempt to solve the issue of bundle size that is already properly solved by tree shaking.

Is that really worth it ? :thinking:

**Comment by alfaproject** [comment]
It looks like the items for version 7 are all done except one. Is there any progress? Feels a bit stagnated ):

**Comment by akakira** [comment]
Do you honestly think this signature change on the subscribe, etc. methods is critical enough to cause billions of lines of code change across the internet?

**Comment by edwardaskew** [comment]
You seem to have "Publish `@rxjs/fetch`" twice. I'm sure it will be an awesome package but it probably only needs to be done once 😋

**Comment by PowerKiKi** [comment]
@benlesh, it seems development toward v8 is picking up lately. However I am not aware that the concerns expressed in https://github.com/ReactiveX/rxjs/issues/6367#issuecomment-1122351023 and https://github.com/ReactiveX/rxjs/issues/6786#issuecomment-1172953044 have been addressed. And it seems a few persons are sharing those concerns.

Is the plan still to split in multiple, possibly redundant, packages ? What's the team opinion about the pitfalls of such a strategy, as experienced by `lodash` and `graphql` (for example) ?

**Comment by 43081j** [comment]
have you considered 8.x being your first esm-only version of rxjs? seems to me it is the ideal opportunity to do that.

we're now at a point where most consumers are on a version of node which is capable of importing ESM packages, and all popular bundlers are too.

anyone who can _only_ use CJS must be on a fairly old node version, so are likely going to be fine sticking to rxjs 7.x.

there's a few hazards and disadvantages with dual packages (esm + cjs), and the complexity of the build scripts for contributors/maintainers etc.

you mentioned you considered publishing CJS and ESM packages separately, but i wouldn't bother to be honest. many other packages have already moved to pure ESM and consumers managed fine, imo we could do the same her.e

**Comment by muuvmuuv** [comment]
Just tested latest alpha release and these errors appear, is that on purpose? If yes, I would go and open issues on GH for these.
![SCR-20240102-odhu](https://github.com/ReactiveX/rxjs/assets/11534760/cb1827e0-6d04-4df5-ad94-aa70c19e9668)

**Comment by benlesh** [comment]
> Wouldn't publishing multiple packages for what is essentially the same code actually increase risk of non tree shakable use-case and thus increase bundle size ?

It shouldn't... `rxjs` itself will re-export `@rxjs/observable`, `@rxjs/fetch`, et al. So there's only really one copy of those dependencies. The only real risk is the same risk we've always had, where a dependency can depend on `rxjs`, and then _you_ can depend on `rxjs` and you end up with two different versions in your codebase... if your bundler/repo isn't set up properly, you're doomed in that scenario even WITHOUT this change.

**Comment by benlesh** [comment]
> Do you honestly think this signature change on the subscribe, etc. methods is critical enough to cause billions of lines of code change across the internet?

Yes. In order to align with [native observables](https://github.com/wicg/observable), the change to `subscribe` is required to move forward. However, you're wrong that it will "cause billions of lines of code change". Whatever version of RxJS that code is using will still exist. There's very, very little chance of any security issues or reasons to change those old versions, and if there were, we'd just fix it and publish a new 7.x or whatever.

**Comment by benlesh** [comment]
> have you considered 8.x being your first esm-only version of rxjs? 

We can't really do this yet. There are way too many people using RxJS with CJS still. Myself included.

**Comment by benlesh** [comment]
For those of you wondering about the path of different packages for each thing... the primary motivator is around how many libraries choose to use some other, untested, and or cobbled-together observable implementation because they "don't want all of RxJS". This causes us to end up shipping our observables alongside other people's observables in the same bundles, and then it causes developers to need to deal with interop, etc.

Ideally, we can convince developers that want observables to use the most battle tested and common implementation, at least until native observables land.

**Comment by stijns96** [comment]
What is the status of this?

**Comment by Alex3917** [comment]
@benlesh Is the idea then that version 8 will eventually be released using a polyfilled version of the Web Platform observable?

**Comment by benlesh** [comment]
There will be an optional polyfill, or an identical observable to directly import. The RxJS observable will pass all web platform tests as well, and there will be some backwards compat solution.

**Comment by wolfmanfx** [comment]
@benlesh Hi - what is the actual state on rxjs 8 in 2026?

**Comment by nhattran998** [comment]
Should we use RxJS in 2026 - 2027 (AI era)? I see the team does not maintain it anymore(1 years)

**Comment by benlesh** [comment]
@nhattran998 yes. Do you see something that is desperate need of a new release? If so, bump the PR or issue. Odds are it's probably not an issue, as every time I see one and think "Oh! This looks important!" I realize quickly after I dig in or stop and think about it that the PR or issue either doesn't have merit or it is centralized around a misunderstanding.

At the end of the day, there's only so many ways to mergeMap an Observable :). And the abstractions are so low-level that they don't require security updates very often, if at all.

Most of the pause on RxJS is the result of waiting for the Web Platform Observable to solidify so we can align to it. There is a 9.0.0-beta release at the moment that is targeting that. But I expect that 9 will remain beta for a long time while the platform settles.
